title: <p align="center"> Phuc (Patrick) Nguyen </p>

logo: "/images/avatar.jpeg?raw=true"

description:
  <p align="center">
  <a href="pdf/CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/phucnh22/">LinkedIn</a> |
  <a href="https://github.com/phucnh22">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently pursueing master degree in Data Science at the <a href="https://www.novaims.unl.pt/">NOVA Information Management School</a>. 
  Before the MSc., I was a management consultant at KPMG working on supply chain management.
  <br><br>
  My areas of interest are <b>MLOps</b>, <b>recommender systems</b>, <b>NLP</b>.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
